NEPT-2073: Add drush command to check iframe usage.
ec-europa/ec-europa-tools pull request #13
Opened 2018-10-25 09:25 UTC by ku-enza

## Changes
Added a drush command to  be run on a subsite to know how much  iframes are used.

## Command
drush chkif

2018-10-26 13:32 UTC, AlbaParrilla approved these changes

2018-10-30 08:07 UTC, ventzie555 requested changes
I confirm the issue Alba found. After inserting iframe from av portal:

<p><iframe frameborder="0" height="480" id="videoplayer" scrolling="no" src="https://europa.eu/!bq38Td" webkitallowfullscre="" width="852"></iframe>en="true" mozallowfullscreen="true" allowFullScreen="true"&gt;</p>

I got:

bash-4.1$ drush chkif
Checking iframes on site: European Commission

Field Name Field Type NId Node Title AV Portal 
body text_with_summary 2 test NO



Other than that, everything looks good.

2018-10-30 08:07 UTC, ventzie555 approved these changes

2018-10-31 10:41 UTC, ventzie555 approved these changes
Now everything seems to be working good!

2018-10-31 13:56 UTC, aritomelo commented on Check_iframes/check_iframes.drush.inc
> +* It will return 0, 1 (iframe), 2 (av-portal iframe), 3 AVportal Old way.
What the difference between 0 and 1?

2018-11-06 14:11 UTC, aritomelo commented
The solution looks great. so I am giving my +1

2018-11-08 10:23 UTC, merged